import type { ServerQuestion } from '../../../shared/src/types.js';

export const GENERAL_KNOWLEDGE_QUESTIONS: ServerQuestion[] = [
  { id: 'gk-001', category: 'General Knowledge', text: 'What is the chemical symbol for gold?', options: ['Go', 'Au', 'Ag', 'Gd'], correctIndex: 1, difficulty: 'easy' },
  { id: 'gk-002', category: 'General Knowledge', text: 'Which planet is known as the Red Planet?', options: ['Venus', 'Jupiter', 'Mars', 'Saturn'], correctIndex: 2, difficulty: 'easy' },
  { id: 'gk-003', category: 'General Knowledge', text: 'What is the largest ocean on Earth?', options: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'], correctIndex: 3, difficulty: 'easy' },
  { id: 'gk-004', category: 'General Knowledge', text: 'Who wrote "Romeo and Juliet"?', options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'], correctIndex: 1, difficulty: 'easy' },
  { id: 'gk-005', category: 'General Knowledge', text: 'What is the capital of Japan?', options: ['Kyoto', 'Osaka', 'Tokyo', 'Seoul'], correctIndex: 2, difficulty: 'easy' },
  { id: 'gk-006', category: 'General Knowledge', text: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Iron', 'Diamond', 'Quartz'], correctIndex: 2, difficulty: 'easy' },
  { id: 'gk-007', category: 'General Knowledge', text: 'How many continents are there?', options: ['5', '6', '7', '8'], correctIndex: 2, difficulty: 'easy' },
  { id: 'gk-008', category: 'General Knowledge', text: 'What is the freezing point of water in Celsius?', options: ['0', '32', '100', '-32'], correctIndex: 0, difficulty: 'easy' },
  { id: 'gk-009', category: 'General Knowledge', text: 'Which animal is known as the King of the Jungle?', options: ['Tiger', 'Elephant', 'Lion', 'Bear'], correctIndex: 2, difficulty: 'easy' },
  { id: 'gk-010', category: 'General Knowledge', text: 'What color do you get by mixing red and yellow?', options: ['Green', 'Orange', 'Purple', 'Brown'], correctIndex: 1, difficulty: 'easy' },
  { id: 'gk-011', category: 'General Knowledge', text: 'In which continent is the Sahara Desert located?', options: ['Asia', 'Africa', 'Australia', 'South America'], correctIndex: 1, difficulty: 'easy' },
  { id: 'gk-012', category: 'General Knowledge', text: 'What is the largest mammal in the world?', options: ['Elephant', 'Blue Whale', 'Giraffe', 'Hippopotamus'], correctIndex: 1, difficulty: 'easy' },
  { id: 'gk-013', category: 'General Knowledge', text: 'How many colors are in a rainbow?', options: ['5', '6', '7', '8'], correctIndex: 2, difficulty: 'easy' },
  { id: 'gk-014', category: 'General Knowledge', text: 'What is the main ingredient in guacamole?', options: ['Tomato', 'Avocado', 'Onion', 'Pepper'], correctIndex: 1, difficulty: 'easy' },
  { id: 'gk-015', category: 'General Knowledge', text: 'Which gas do plants absorb from the atmosphere?', options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'], correctIndex: 2, difficulty: 'easy' },
  { id: 'gk-016', category: 'General Knowledge', text: 'Who painted the Mona Lisa?', options: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet'], correctIndex: 2, difficulty: 'easy' },
  { id: 'gk-017', category: 'General Knowledge', text: 'What is the currency of the United Kingdom?', options: ['Euro', 'Dollar', 'Pound Sterling', 'Yen'], correctIndex: 2, difficulty: 'easy' },
  { id: 'gk-018', category: 'General Knowledge', text: 'Which sense is associated with the olfactory nerve?', options: ['Sight', 'Hearing', 'Smell', 'Taste'], correctIndex: 2, difficulty: 'easy' },
  { id: 'gk-019', category: 'General Knowledge', text: 'What is the tallest mountain in the world?', options: ['K2', 'Mount Everest', 'Mount Kilimanjaro', 'Denali'], correctIndex: 1, difficulty: 'easy' },
  { id: 'gk-020', category: 'General Knowledge', text: 'What is the primary language spoken in Brazil?', options: ['Spanish', 'Portuguese', 'English', 'French'], correctIndex: 1, difficulty: 'easy' },
  { id: 'gk-021', category: 'General Knowledge', text: 'How many legs does a spider have?', options: ['6', '8', '10', '12'], correctIndex: 1, difficulty: 'easy' },
  { id: 'gk-022', category: 'General Knowledge', text: 'What is the boiling point of water in Celsius?', options: ['50', '90', '100', '120'], correctIndex: 2, difficulty: 'easy' },
  { id: 'gk-023', category: 'General Knowledge', text: 'Which country is home to the kangaroo?', options: ['New Zealand', 'South Africa', 'Australia', 'Brazil'], correctIndex: 2, difficulty: 'easy' },
  { id: 'gk-024', category: 'General Knowledge', text: 'What is the closest planet to the Sun?', options: ['Venus', 'Earth', 'Mercury', 'Mars'], correctIndex: 2, difficulty: 'easy' },
  
  { id: 'gk-025', category: 'General Knowledge', text: 'What is the chemical symbol for Iron?', options: ['Ir', 'In', 'Fe', 'I'], correctIndex: 2, difficulty: 'medium' },
  { id: 'gk-026', category: 'General Knowledge', text: 'Who is the author of the Harry Potter series?', options: ['J.R.R. Tolkien', 'J.K. Rowling', 'Stephen King', 'George R.R. Martin'], correctIndex: 1, difficulty: 'medium' },
  { id: 'gk-027', category: 'General Knowledge', text: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2, difficulty: 'medium' },
  { id: 'gk-028', category: 'General Knowledge', text: 'In what year did the Titanic sink?', options: ['1905', '1912', '1918', '1923'], correctIndex: 1, difficulty: 'medium' },
  { id: 'gk-029', category: 'General Knowledge', text: 'What is the largest desert in the world (including cold deserts)?', options: ['Sahara', 'Arabian', 'Gobi', 'Antarctic Desert'], correctIndex: 3, difficulty: 'medium' },
  { id: 'gk-030', category: 'General Knowledge', text: 'Who discovered penicillin?', options: ['Marie Curie', 'Alexander Fleming', 'Louis Pasteur', 'Isaac Newton'], correctIndex: 1, difficulty: 'medium' },
  { id: 'gk-031', category: 'General Knowledge', text: 'Which element has the atomic number 1?', options: ['Helium', 'Oxygen', 'Hydrogen', 'Carbon'], correctIndex: 2, difficulty: 'medium' },
  { id: 'gk-032', category: 'General Knowledge', text: 'What is the smallest country in the world?', options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'], correctIndex: 1, difficulty: 'medium' },
  { id: 'gk-033', category: 'General Knowledge', text: 'What is the longest river in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], correctIndex: 1, difficulty: 'medium' },
  { id: 'gk-034', category: 'General Knowledge', text: 'Who developed the theory of general relativity?', options: ['Isaac Newton', 'Galileo Galilei', 'Albert Einstein', 'Nikola Tesla'], correctIndex: 2, difficulty: 'medium' },
  { id: 'gk-035', category: 'General Knowledge', text: 'Which ancient wonder was located in Alexandria, Egypt?', options: ['Colossus', 'Hanging Gardens', 'Lighthouse', 'Mausoleum'], correctIndex: 2, difficulty: 'medium' },
  { id: 'gk-036', category: 'General Knowledge', text: 'In Greek mythology, who is the god of the sea?', options: ['Zeus', 'Hades', 'Poseidon', 'Apollo'], correctIndex: 2, difficulty: 'medium' },
  { id: 'gk-037', category: 'General Knowledge', text: 'What is the currency of Japan?', options: ['Won', 'Yen', 'Yuan', 'Ringgit'], correctIndex: 1, difficulty: 'medium' },
  { id: 'gk-038', category: 'General Knowledge', text: 'Which metal is liquid at room temperature?', options: ['Lead', 'Iron', 'Mercury', 'Zinc'], correctIndex: 2, difficulty: 'medium' },
  { id: 'gk-039', category: 'General Knowledge', text: 'Who wrote "1984"?', options: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'F. Scott Fitzgerald'], correctIndex: 1, difficulty: 'medium' },
  { id: 'gk-040', category: 'General Knowledge', text: 'What is the main gas found in the air we breathe?', options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'], correctIndex: 2, difficulty: 'medium' },
  { id: 'gk-041', category: 'General Knowledge', text: 'What is the capital of Canada?', options: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'], correctIndex: 3, difficulty: 'medium' },
  { id: 'gk-042', category: 'General Knowledge', text: 'Which planet is famous for its rings?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], correctIndex: 1, difficulty: 'medium' },
  { id: 'gk-043', category: 'General Knowledge', text: 'What is the hardest rock?', options: ['Granite', 'Basalt', 'Diamond', 'Marble'], correctIndex: 2, difficulty: 'medium' },
  { id: 'gk-044', category: 'General Knowledge', text: 'Who was the first person to walk on the moon?', options: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'Michael Collins'], correctIndex: 2, difficulty: 'medium' },
  { id: 'gk-045', category: 'General Knowledge', text: 'What is the national flower of Japan?', options: ['Lotus', 'Cherry Blossom', 'Rose', 'Chrysanthemum'], correctIndex: 1, difficulty: 'medium' },
  { id: 'gk-046', category: 'General Knowledge', text: 'Which organ in the human body produces insulin?', options: ['Liver', 'Kidney', 'Pancreas', 'Heart'], correctIndex: 2, difficulty: 'medium' },
  { id: 'gk-047', category: 'General Knowledge', text: 'What is the largest bone in the human body?', options: ['Femur', 'Tibia', 'Humerus', 'Fibula'], correctIndex: 0, difficulty: 'medium' },
  { id: 'gk-048', category: 'General Knowledge', text: 'Who painted the Sistine Chapel ceiling?', options: ['Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello'], correctIndex: 1, difficulty: 'medium' },
  
  { id: 'gk-049', category: 'General Knowledge', text: 'What is the rarest blood type in humans?', options: ['O negative', 'AB negative', 'A negative', 'B negative'], correctIndex: 1, difficulty: 'hard' },
  { id: 'gk-050', category: 'General Knowledge', text: 'Which philosopher said "I think, therefore I am"?', options: ['Socrates', 'Plato', 'Aristotle', 'René Descartes'], correctIndex: 3, difficulty: 'hard' },
  { id: 'gk-051', category: 'General Knowledge', text: 'What is the half-life of Carbon-14?', options: ['5730 years', '10000 years', '2500 years', '1 million years'], correctIndex: 0, difficulty: 'hard' },
  { id: 'gk-052', category: 'General Knowledge', text: 'In which year did the Byzantine Empire fall?', options: ['1204', '1350', '1453', '1492'], correctIndex: 2, difficulty: 'hard' },
  { id: 'gk-053', category: 'General Knowledge', text: 'Who was the first woman to win a Nobel Prize?', options: ['Mother Teresa', 'Rosalind Franklin', 'Marie Curie', 'Ada Lovelace'], correctIndex: 2, difficulty: 'hard' },
  { id: 'gk-054', category: 'General Knowledge', text: 'What is the capital city of Mongolia?', options: ['Astana', 'Ulaanbaatar', 'Bishkek', 'Tashkent'], correctIndex: 1, difficulty: 'hard' },
  { id: 'gk-055', category: 'General Knowledge', text: 'What is the study of mushrooms called?', options: ['Mycology', 'Botany', 'Phycology', 'Entomology'], correctIndex: 0, difficulty: 'hard' },
  { id: 'gk-056', category: 'General Knowledge', text: 'Which element has the highest melting point?', options: ['Platinum', 'Tungsten', 'Osmium', 'Titanium'], correctIndex: 1, difficulty: 'hard' },
  { id: 'gk-057', category: 'General Knowledge', text: 'Who composed the "Symphonie Fantastique"?', options: ['Ludwig van Beethoven', 'Hector Berlioz', 'Franz Schubert', 'Richard Wagner'], correctIndex: 1, difficulty: 'hard' },
  { id: 'gk-058', category: 'General Knowledge', text: 'What is the smallest muscle in the human body?', options: ['Stapedius', 'Masseter', 'Sartorius', 'Deltoid'], correctIndex: 0, difficulty: 'hard' },
  { id: 'gk-059', category: 'General Knowledge', text: 'Which treaty ended the War of 1812?', options: ['Treaty of Paris', 'Treaty of Versailles', 'Treaty of Ghent', 'Treaty of Tordesillas'], correctIndex: 2, difficulty: 'hard' },
  { id: 'gk-060', category: 'General Knowledge', text: 'What is the standard unit of luminous intensity in the SI system?', options: ['Lumen', 'Lux', 'Candela', 'Watt'], correctIndex: 2, difficulty: 'hard' },
];
